umichdu/__init__.py
from flask import Flask, session, g, render_template
from flask_openid import OpenID

app = Flask(__name__)
app.config.from_object('websiteconfig')

from umichdu.openid_auth import DatabaseOpenIDStore
oid = OpenID(app, store_factory=DatabaseOpenIDStore)


@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404


@app.before_request
def load_current_user():
    g.user = User.query.filter_by(openid=session['openid']).first() \
        if 'openid' in session else None


@app.teardown_request
def remove_db_session(exception):
    db_session.remove()


from umichdu.views import general
from umichdu.views import parent
from umichdu.views import greek
from umichdu.views import chapter
from umichdu.views import history
from umichdu.views import recruit
app.register_blueprint(general.mod)
app.register_blueprint(parent.mod)
app.register_blueprint(greek.mod)
app.register_blueprint(chapter.mod)
app.register_blueprint(history.mod)
app.register_blueprint(recruit.mod)

from umichdu.database import User, db_session
from umichdu import utils

app.jinja_env.filters['datetimeformat'] = utils.format_datetime
app.jinja_env.filters['timedeltaformat'] = utils.format_timedelta
app.jinja_env.filters['displayopenid'] = utils.display_openid

umichdu/views/chapter.py
from flask import Blueprint, render_template, jsonify

mod = Blueprint('chapter', __name__, url_prefix='/chapter')


@mod.route('/')
def index():
    return render_template('chapter/index.html')


@mod.route('/brothers/')
def brothers():
	return render_template('chapter/brothers.html')


@mod.route('/alumni/')
def alumni():
	return render_template('chapter/alumni.html')

umichdu/views/general.py
from flask import Blueprint, render_template, session, redirect, url_for, \
     request, flash, g, jsonify, abort
from flask_openid import COMMON_PROVIDERS
from umichdu import oid
from umichdu.utils import requires_login, request_wants_json
from umichdu.database import db_session, User

mod = Blueprint('general', __name__)


@mod.route('/')
def index():
    return render_template('general/index.html')


@mod.route('/logout/')
def logout():
    if 'openid' in session:
        flash(u'Logged out')
        del session['openid']
    return redirect(request.referrer or url_for('general.index'))


@mod.route('/login/', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    if g.user is not None:
        return redirect(url_for('general.index'))
    if 'cancel' in request.form:
        flash(u'Cancelled. The OpenID was not changed.')
        return redirect(oid.get_next_url())
    openid = request.values.get('openid')
    if not openid:
        openid = COMMON_PROVIDERS.get(request.args.get('provider'))
    if openid:
        return oid.try_login(openid, ask_for=['fullname', 'nickname'])
    error = oid.fetch_error()
    if error:
        flash(u'Error: ' + error)
    return render_template('general/login.html', next=oid.get_next_url())


@mod.route('/first-login/', methods=['GET', 'POST'])
def first_login():
    if g.user is not None or 'openid' not in session:
        return redirect(url_for('.login'))
    if request.method == 'POST':
        if 'cancel' in request.form:
            del session['openid']
            flash(u'Login was aborted')
            return redirect(url_for('general.login'))
        db_session.add(User(request.form['name'], session['openid']))
        db_session.commit()
        flash(u'Successfully created profile and logged in')
        return redirect(oid.get_next_url())
    return render_template('general/first_login.html',
                           next=oid.get_next_url(),
                           openid=session['openid'])


@mod.route('/profile/', methods=['GET', 'POST'])
@requires_login
def profile():
    name = g.user.name
    if request.method == 'POST':
        name = request.form['name'].strip()
        if not name:
            flash(u'Error: a name is required')
        else:
            g.user.name = name
            db_session.commit()
            flash(u'User profile updated')
            return redirect(url_for('.index'))
    return render_template('general/profile.html', name=name)


@mod.route('/profile/change-openid/', methods=['GET', 'POST'])
@requires_login
@oid.loginhandler
def change_openid():
    if request.method == 'POST':
        if 'cancel' in request.form:
            flash(u'Cancelled. The OpenID was not changed.')
            return redirect(oid.get_next_url())
    openid = request.values.get('openid')
    if not openid:
        openid = COMMON_PROVIDERS.get(request.args.get('provider'))
    if openid:
        return oid.try_login(openid)
    error = oid.fetch_error()
    if error:
        flash(u'Error: ' + error)
    return render_template('general/change_openid.html',
                           next=oid.get_next_url())


@oid.after_login
def create_or_login(resp):
    session['openid'] = resp.identity_url
    user = g.user or User.query.filter_by(openid=resp.identity_url).first()
    if user is None:
        return redirect(url_for('.first_login', next=oid.get_next_url(),
                                name=resp.fullname or resp.nickname))
    if user.openid != resp.identity_url:
        user.openid = resp.identity_url
        db_session.commit()
        flash(u'OpenID identity changed')
    else:
        flash(u'Successfully signed in')
    return redirect(oid.get_next_url())

umichdu/views/greek.py
from flask import Blueprint, render_template, jsonify

mod = Blueprint('greek', __name__, url_prefix='/greek')


@mod.route('/')
def index():
    return render_template('greek/index.html')

umichdu/views/history.py
from flask import Blueprint, render_template, jsonify

mod = Blueprint('history', __name__, url_prefix='/history')


@mod.route('/')
def index():
    return render_template('history/index.html')

umichdu/views/parent.py
from flask import Blueprint, render_template, jsonify

mod = Blueprint('parent', __name__, url_prefix='/parent')


@mod.route('/')
def index():
    return render_template('parent/index.html')

umichdu/views/recruit.py
from flask import Blueprint, render_template, jsonify

mod = Blueprint('recruit', __name__, url_prefix='/recruit')


@mod.route('/')
def index():
    return render_template('recruit/index.html')

umichdu/templates/_twitter.html
{% macro tweet_box(tweets, limit=none) %}
  <div class=twitter>
    <ul>
    {%- for tweet in tweets.get(limit) %}
      <li>
        <a href="http://twitter.com/{{ tweet.user }}">{{ tweet.user }}</a>:
          {{ tweet.text|urlize }}
        <span class=meta>&mdash; {% if tweet.pub_date %}{{ tweet.pub_date|timedeltaformat }} ago {% endif %}via {{ tweet.via }}</span>
    {%- endfor %}
    </ul>
  </div>
{% endmacro %}

umichdu/templates/chapter/alumni.html
{% extends "chapter/layout.html" %}
{% block body %}

{% endblock %}

umichdu/templates/chapter/brothers.html
{% extends "chapter/layout.html" %}
{% block body %}

{% endblock %}

umichdu/templates/chapter/index.html
{% extends "chapter/layout.html" %}
{% block body %}
<p>
The University of Michigan chapter of Delta Upsilon was founded in 1876 by three men who believed in the ideals of the Anti-Secret Society as it was formerly known. Eleven more men joined in the spring, and Delta Upsilon has been a presence on campus ever since.
<p>
The iconic chapter house was the first house built exclusively for fraternity use in 1903. Famed architect Albert Kahn—who also designed Hill Auditorium—created an open floor layout, reflecting the ideals of non-secrecy. The house is an English Tudor style that has detailed wooded craftsmanship with carved wooden fraternity symbols sprinkled throughout the house.
<p>
The University of Michigan Delta Upsilon endured an unexpected hardship in the summer of 2008 when the chapter house burned down. Forced to live in residential houses for four years, the brotherhood managed to keep numbers relatively steady, but certainly missed the central meeting place a chapter house offers. 
<p>
Four years later, following Albert Kahn’s original design, the chapter house was finally completed in September 2012. With brother and architect Jeff Scott overseeing the project, the Delta Upsilon house is an unbelievable space, allowing the brotherhood to flourish again. The chapter also rescued a puppy, Emma, who lives in the chapter house.

{% endblock %}

umichdu/templates/chapter/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='community.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Community</span></h1>
{% endblock %}

umichdu/templates/general/first_login.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='login.png') }}); }
  </style>
{% endblock %}
{% block title %}First Login{% endblock %}
{% block body %}
  <h2>This is your First Login</h2>
  <form action="{{ url_for('general.first_login') }}" method=post>
    <p>
      This is your first login on this website.  You are about to sign
      in with the following OpenID: <a href="{{ openid }}">{{
        openid|displayopenid }}</a>
    <p>
      Before you can use this site we need a name for you.  This is what
      will be displayed next to all of your public contributions to this
      site.  Choose wisely because you cannot change this value later:
    <dl>
      <dt>Name:
      <dd><input type=text name=name value="{{ request.values.name }}" size=30>
    </dl>
    <p>
      <input type=hidden name=next value="{{ next }}">
      <input type=submit value=Continue>
      <input type=submit name=cancel value=Cancel>
  </form>
{% endblock %}

umichdu/templates/general/index.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
{% endblock %}

{% block body_title %}
  {{ super() }}
{% endblock %}

{% block body %}

<p>
Delta Upsilon, an international fraternity founded in 1834 at Williams College on the principle of non-secrecy, is committed to building better men by espousing the four founding principles: the promotion of friendship, the development of character, the diffusion of liberal culture and the advancement of justice. 
<p>
Founded in 1876, the University of Michigan chapter has been a stable on campus for well over a hundred years and continues to contribute to every aspect of campus life: academic, athletic, social, student government and philanthropic. Our iconic 1903 chapter house was completely rebuilt and finished in August 2012, allowing DU to continue building on its venerable tradition at Michigan.
<p>
We welcome you to our website and invite you to explore the past, present, and future of the University of Michigan Chapter of Delta Upsilon. 
<p>
Dikaia Upotheke - Go Blue!

{% endblock %}

umichdu/templates/general/profile.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='profile.png') }}); }
  </style>
{% endblock %}
{% block title %}Profile{% endblock %}
{% block body %}
  <form action="" method=post>
    <p>
      Here you can change the profile information used for this
      website.  Please keep in mind that you can only have one
      OpenID identity linked to this account, if you change it
      the old one will no longer be able to sign in.
    <dl class=formlist>
      <dt>Name:
      <dd><input type=text name=name value="{{ name }}" size=30>
      <dt>OpenID:
      <dd>
        <span class=disabled>{{ g.user.openid|displayopenid }}</span>
        (<a href="{{ url_for('.change_openid') }}">change</a>)
    </dl>
    <p>
      <input type=submit value="Update profile">
  </form>
{% endblock %}

umichdu/templates/greek/index.html
{% extends "history/layout.html" %}
{% block body %}

{% endblock %}

umichdu/templates/greek/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='community.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Community</span></h1>
{% endblock %}

umichdu/templates/history/index.html
{% extends "history/layout.html" %}
{% block body %}
<p>
Delta Upsilon is the sixth oldest fraternity in North America at 178 years old. When students and the faculty became concerned with the secret activities of two fraternities at Williams College in Massachusetts, Delta Upsilon was founded. Arguing that the use of fraternities for political gain—such as successfully placing members in high office not for their merit but for their membership in a certain brotherhood—was wrong, sophomores Stephen Field, Lewis Lockwood and Francis Tappan recruited 30 likeminded men. Together, they endeavored to build a brotherhood with the motto “Ouden Adelon,” meaning nothing secret, and fought to advance justice and liberal culture. They saw no need to secret rituals.
<p>
As the non-secret fraternity movement began to spread, Delta Upsilon established chapters all over the country and eventually into Canada. It has a proud history of producing great scholars, public servants, businessmen, athletes, scientists, writers and entertainers. For example:

{% endblock %}

umichdu/templates/history/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='community.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Community</span></h1>
{% endblock %}

umichdu/templates/layout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% block head %}
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Delta Upsilon | University of Michigan</title>
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Abel|Satisfy' rel='stylesheet' type='text/css' />

<link href="{{ url_for('static', filename='default.css') }}" rel="stylesheet" type="text/css" media="all" />
<!--[if IE 6]>
<link href="default_ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->
<script type=text/javascript
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
{% endblock %}
</head>
<body>
<div id="wrapper">
  <div id="header-wrapper">
    <div id="header">
      <div id="logo">
        <h1><a href="#">Delta Upsilon</a></h1>
      <p>University of Michigan Chapter</p>
      </div>
      <div id="menu">
        <ul>
            <li><a href="{{ url_for('general.index') }}">Home</a></li>
            <li><a href="{{ url_for('parent.index') }}">Parents</a></li>
              <li><a href="{{ url_for('greek.index') }}">Greek Life</a></li>
              <li><a href="{{ url_for('chapter.index') }}">Our Chapter</a></li>
              <li><a href="{{ url_for('recruit.index') }}">Recruitment</a></li>
              <li><a href="{{ url_for('history.index') }}">History</a></li>
              <!--<li><a href="{{ url_for('chapter.brothers') }}">Brothers</a></li>
              <li><a href="{{ url_for('chapter.alumni') }}">Alumni</a></li>-->
          </ul>
      </div>
    </div>
  </div>
  <!-- <div id="banner"><img src="{{ url_for('static', filename='header-img.jpg') }}" width="1120" height="500" alt="" /></div> -->
  <div id="page-wrapper">
  	<div id="page">
		<div id="wide-content">
			<div>
				{% block body %}{% endblock %}
  			</div>
		</div>
	</div>
  </div>
</div>
<div id="footer">
  <p>&copy; Copyright 2012 by <a href=http://grahammackie.com/>Graham Mackie </a>
    {% if g.user %}
    <a href="{{ url_for('general.profile') }}">profile</a> /
    <a href="{{ url_for('general.logout') }}" title="signed in as {{
      g.user.name }} [{{ g.user.openid }}]{% if g.user.is_admin
      %} - Administrator{% endif %}">sign out</a>
    {% else %}
    <a href="{{ url_for('general.login') }}">sign in</a>
    {% endif %}</p>
</div>
</body>
</html>

umichdu/templates/parent/index.html
{% extends "history/layout.html" %}
{% block body %}
<div id="page">
			<div id="wide-content">
				<div>
<p>
We understand the reputation that is attached to fraternities can be disconcerting for parents. At Delta Upsilon, however, we pride ourselves on not being a stereotypical fraternity. 
<p>
To put it simply: we do not haze. As a fraternity founded on justice and non-secrecy, hazing runs contrary to what we stand for and believe in. Our goal of building better men does not require it—indeed, we believe that hazing does the opposite. 
<p>
Likewise, we recognize that above anything else, we are students here at the University of Michigan. Never will fraternity business come before schoolwork. Delta Upsilon holds its brothers accountable for their performance in the classroom and considers its members’ academic standing to be a direct reflection of the fraternity. Joining DU will not destroy your GPA; rather, it will serve as an academic resource with a diverse group of brothers covering many schools and majors throughout the university.
<p>
If you have any questions about the pledgeship, academics, or our fraternity, please feel free to contact:
<p>
Kevin Lass
President
(contact information)
<a href="mailto:kmlass@umich.edu">email</a>
<p>
Sean Carney
Vice President of New Member Education
(contact information)
<p>
An Nguyen
Vice President for Scholarship
(contact information)
</div>
			</div>
		</div>
{% endblock %}

umichdu/templates/parent/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='community.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Community</span></h1>
{% endblock %}

umichdu/templates/recruit/index.html
{% extends "history/layout.html" %}
{% block body %}
<p>
Delta Upsilon participates is both Fall and Winter rush and is constantly looking for any Michigan student who would add to the fraternity. The Fall 2012 Rush dates are:
<li>
<ul>Sept 11th Open House – 1331 Hill 6-9PM
<ul>Sept 18th Cookout – 1331 Hill 6-9PM
<ul>Sept 19th Pizza Night – 1331 Hill 6-9PM
<ul>Sept 20th – Invite Only
</li>
<p>
If you have any questions regarding recruitment, contact Connor Jennings, Vice President for Recruitment at (616) 566-9756 or <a href="mailto:jmbarch@umich.edu">jmbarch@umich.edu</a>. Also, join the rush <a href="www.facebook.com/groups/durush">Facebook group</a>. 

{% endblock %}

umichdu/templates/recruit/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='community.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Community</span></h1>
{% endblock %}